### ISSUE TITLE
Request for Dataset and Execution Guide for your gsplat Repository

### ISSUE THREAD

**Issue by svvj** [inuex35/gsplat#3]
Hello @inuex35,

I have been following your project with great interest. While trying out 360-Gaussian-Splatting, I couldn't achieve good results and was searching for an alternative when I came across your gsplat repository, which works well.

I would like to verify the performance using your dataset. Could you share the dataset and the execution guide with me?

Additionally, if there's anything I can assist with during development, I would be more than happy to contribute.

Thank you!

**Comment by inuex35** [comment]
Hello, here is my data.
https://dtbn.jp/k2BFTwXe
My current interest is in developing hardware with an RTK 360 camera. I think the performance of this implementation should be evaluated with an official dataset.
